Fix/rpcs
Simon-Deuring/labgrid-frontend-mle pull request #99
Opened 2022-01-15 19:54 UTC by deathcat0011

* Re-added acquired_resource field in dictionary returned by the places rpc

2022-01-15 22:37 UTC, Simon-Deuring approved these changes

2022-01-16 22:06 UTC, Simon-Deuring requested changes
The result looks good. However, I imaged having an array of resource objects instead of an array of arrays. Could you insert the marked name into the resource object for every resource and remove the second level of arrays?

![image](https://user-images.githubusercontent.com/33379546/149679770-c3a8782a-005d-416e-b299-f1bf28ef685a.png)

This is how it should look like:

![image](https://user-images.githubusercontent.com/33379546/149679905-1137bb17-54b2-4275-a8e1-f1ebee78a238.png)

If possible you could also add the fields "place" and "target"/"exporter" for each resource.

2022-01-17 19:07 UTC, deathcat0011 commented
I have now changed the returned data to contain the acquired resources as list of resource keys. Sadly it is not possible at the moment to also return the user who holds the place lock.

2022-01-17 19:21 UTC, Simon-Deuring approved these changes

2022-01-17 19:22 UTC, merged